application: weightmeter-hrd
version: 6
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  login: required

- url: /.*
  script: weightmeter.app
  login: required

libraries:
- name: django
  version: "1.2"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
